### ISSUE TITLE
https://mcim.z0z0r4.top/ 挂了

### ISSUE THREAD

**Issue by zkitefly** [z0z0r4/mcim#56]

**Comment by z0z0r4** [comment]
wow，原来真的有人在用

抱歉我备案掉了，我切下解析

**Comment by z0z0r4** [comment]
![16a6c58f9ffb8d243827c26fa986a89d](https://github.com/z0z0r4/mcim/assets/78744121/02b8d2f6-7ea8-4e43-8cfb-a36c933c7e08)

暑假再期待吧.jpg

**Comment by z0z0r4** [comment]
正在 dev 分支下测试运行中
